### ISSUE TITLE
Migrate code from message_data

### ISSUE THREAD

**Issue by khaeru** [iiasa/message-ix-models#4]
This is a tracking issue for other issues/PRs to migrate code from `message_data` to this package.

- [x] `.tools.context`: Context class used for carrying settings and configuration values. → #5
- [x] More pieces of the command-line interface (CLI). → #8
- [x] `model.build` and `model.bare`: code that creates the "bare"/empty MESSAGEix-GLOBIOM reference energy system (RES), without any data. → #9
- [x] `model.disutility`: generalized disutility formulation. —#13
- [x] `.tools.cache` —#26
- ~`.reporting`: Core reporting configuration and `global.yaml`.~ rolled into #27
- [x] Codes for retrieving/reading/processing certain input data:
  - [x] `.tools.gea`: GEA database. —#162
  - ~`.tools.ssp`: SSP database.~ Superseded by #125
  - [x] `.tools.iea_eei`: IEA energy efficiency indicators (EEI) database. —#162
- [x] General documentation about development.
  - #226

**Comment by khaeru** [comment]
Closing, as the checklist is completed. Some other items are preserved in still-open issues and PRs like #27 and #254.
